#define _GNU_SOURCE
#include <unistd.h>
#include <stdio.h>
#include <pthread.h>
#include <sched.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <sys/time.h>
#include <sys/param.h>
#include <errno.h>
#include <limits.h>

#define memory_barrier() __asm ("" ::: "memory")
#define pause() __asm  ("rep ; nop" ::: "memory")

#define CACHELINE_SIZE	64
#define CACHE_ALIGNED	__attribute__((aligned(CACHELINE_SIZE)))

struct count
{
	unsigned long long total;
	unsigned long long diff;
} __attribute__((aligned(128)));

struct count *gcount __attribute__((aligned(128)));

struct {
	pthread_spinlock_t testlock;
	char pad[64];
} test CACHE_ALIGNED;
#define lock() pthread_spin_lock(&test.testlock)
#define unlock() pthread_spin_unlock(&test.testlock)

static void __attribute__((constructor)) init_spin(void)
{
	pthread_spin_init(&test.testlock, 0);
}

#define HASHBUF 20

struct SHA1_CTX
{
    uint32_t state[5];
    uint32_t count[2];
    uint8_t  buffer[64];
};

typedef struct SHA1_CTX SHA1_CTX;

/* The time consumed by one update is about 200 TSCs.  */
static int delay_time_unlocked = 600;

struct ops
{
	void *(*test) (void *arg);
} *ops;

void *work_thread (void *arg);

void test_threads (int numthreads);

#define constant_time 3
#define iterations LONG_MAX

static volatile int start_thread;
static volatile int stop_flag;

/* Delay some fixed time */
	static void
delay_tsc (unsigned n)
{
	unsigned long long start, current, diff;
	unsigned int aux;
	start = __builtin_ia32_rdtscp (&aux);
	while (1)
	{
		current = __builtin_ia32_rdtscp (&aux);
		diff = current - start;
		if (diff < n)
			pause ();
		else
			break;
	}
}

static void
wait_a_bit (int delay_time)
{
	if (delay_time > 0)
		delay_tsc (delay_time);
}

/* Hashwork */
/*
SHA-1 in C
By Steve Reid <sreid@sea-to-sky.net>
100% Public Domain

-----------------
Modified 7/98
By James H. Brown <jbrown@burgoyne.com>
Still 100% Public Domain

Corrected a problem which generated improper hash values on 16 bit machines
Routine SHA1Update changed from
  void SHA1Update(SHA1_CTX* context, unsigned char* data, unsigned int
len)
to
  void SHA1Update(SHA1_CTX* context, unsigned char* data, unsigned
long len)

The 'len' parameter was declared an int which works fine on 32 bit machines.
However, on 16 bit machines an int is too small for the shifts being done
against
it.  This caused the hash function to generate incorrect values if len was
greater than 8191 (8K - 1) due to the 'len << 3' on line 3 of SHA1Update().

Since the file IO in main() reads 16K at a time, any file 8K or larger would
be guaranteed to generate the wrong hash (e.g. Test Vector #3, a million
"a"s).

I also changed the declaration of variables i & j in SHA1Update to
unsigned long from unsigned int for the same reason.

These changes should make no difference to any 32 bit implementations since
an
int and a long are the same size in those environments.

--
I also corrected a few compiler warnings generated by Borland C.
1. Added #include <process.h> for exit() prototype
2. Removed unused variable 'j' in SHA1Final
3. Changed exit(0) to return(0) at end of main.

ALL changes I made can be located by searching for comments containing 'JHB'
-----------------
Modified 8/98
By Steve Reid <sreid@sea-to-sky.net>
Still 100% public domain

1- Removed #include <process.h> and used return() instead of exit()
2- Fixed overwriting of finalcount in SHA1Final() (discovered by Chris Hall)
3- Changed email address from steve@edmweb.com to sreid@sea-to-sky.net

-----------------
Modified 4/01
By Saul Kravitz <Saul.Kravitz@celera.com>
Still 100% PD
Modified to run on Compaq Alpha hardware.

-----------------
Modified 07/2002
By Ralph Giles <giles@ghostscript.com>
Still 100% public domain
modified for use with stdint types, autoconf
code cleanup, removed attribution comments
switched SHA1Final() argument order for consistency
use SHA1_ prefix for public api
move public api to sha1.h
*/

/*
Test Vectors (from FIPS PUB 180-1)
"abc"
  A9993E36 4706816A BA3E2571 7850C26C 9CD0D89D
"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"
  84983E44 1C3BD26E BAAE4AA1 F95129E5 E54670F1
A million repetitions of "a"
  34AA973C D4C4DAA4 F61EEB2B DBAD2731 6534016F
*/

/* public api for steve reid's public domain SHA-1 implementation */
/* this file is in the public domain */

#define rol rotl32
static inline __attribute__((always_inline)) uint32_t rotl32 ( uint32_t x, int8_t r )
{
	  return (x << r) | (x >> (32 - r));
}
/* blk0() and blk() perform the initial expand. */
/* I got the idea of expanding during the round function from SSLeay */
/* FIXME: can we do this in an endian-proof way? */

#ifdef WORDS_BIGENDIAN
#define blk0(i) block->l[i]
#else
#define blk0(i) (block->l[i] = (rol(block->l[i],24)&0xFF00FF00) | (rol(block->l[i],8)&0x00FF00FF))
#endif
#define blk(i) (block->l[i&15] = rol(block->l[(i+13)&15]^block->l[(i+8)&15] ^ block->l[(i+2)&15]^block->l[i&15],1))

/* (R0+R1), R2, R3, R4 are the different operations used in SHA1 */
#define R0(v,w,x,y,z,i) z+=((w&(x^y))^y)+blk0(i)+0x5A827999+rol(v,5);w=rol(w,30);
#define R1(v,w,x,y,z,i) z+=((w&(x^y))^y)+blk(i)+0x5A827999+rol(v,5);w=rol(w,30);
#define R2(v,w,x,y,z,i) z+=(w^x^y)+blk(i)+0x6ED9EBA1+rol(v,5);w=rol(w,30);
#define R3(v,w,x,y,z,i) z+=(((w|x)&y)|(w&x))+blk(i)+0x8F1BBCDC+rol(v,5);w=rol(w,30);
#define R4(v,w,x,y,z,i) z+=(w^x^y)+blk(i)+0xCA62C1D6+rol(v,5);w=rol(w,30);

/* Hash a single 512-bit block. This is the core of the algorithm. */
static void SHA1_Transform(uint32_t state[5], const uint8_t buffer[64])
{
    uint32_t a, b, c, d, e;
    typedef union {
        uint8_t c[64];
        uint32_t l[16];
    } CHAR64LONG16;
    CHAR64LONG16* block;

    block = (CHAR64LONG16*)buffer;

    /* Copy context->state[] to working vars */
    a = state[0];
    b = state[1];
    c = state[2];
    d = state[3];
    e = state[4];

    /* 4 rounds of 20 operations each. Loop unrolled. */
    R0(a,b,c,d,e, 0); R0(e,a,b,c,d, 1); R0(d,e,a,b,c, 2); R0(c,d,e,a,b, 3);
    R0(b,c,d,e,a, 4); R0(a,b,c,d,e, 5); R0(e,a,b,c,d, 6); R0(d,e,a,b,c, 7);
    R0(c,d,e,a,b, 8); R0(b,c,d,e,a, 9); R0(a,b,c,d,e,10); R0(e,a,b,c,d,11);
    R0(d,e,a,b,c,12); R0(c,d,e,a,b,13); R0(b,c,d,e,a,14); R0(a,b,c,d,e,15);
    R1(e,a,b,c,d,16); R1(d,e,a,b,c,17); R1(c,d,e,a,b,18); R1(b,c,d,e,a,19);
    R2(a,b,c,d,e,20); R2(e,a,b,c,d,21); R2(d,e,a,b,c,22); R2(c,d,e,a,b,23);
    R2(b,c,d,e,a,24); R2(a,b,c,d,e,25); R2(e,a,b,c,d,26); R2(d,e,a,b,c,27);
    R2(c,d,e,a,b,28); R2(b,c,d,e,a,29); R2(a,b,c,d,e,30); R2(e,a,b,c,d,31);
    R2(d,e,a,b,c,32); R2(c,d,e,a,b,33); R2(b,c,d,e,a,34); R2(a,b,c,d,e,35);
    R2(e,a,b,c,d,36); R2(d,e,a,b,c,37); R2(c,d,e,a,b,38); R2(b,c,d,e,a,39);
    R3(a,b,c,d,e,40); R3(e,a,b,c,d,41); R3(d,e,a,b,c,42); R3(c,d,e,a,b,43);
    R3(b,c,d,e,a,44); R3(a,b,c,d,e,45); R3(e,a,b,c,d,46); R3(d,e,a,b,c,47);
    R3(c,d,e,a,b,48); R3(b,c,d,e,a,49); R3(a,b,c,d,e,50); R3(e,a,b,c,d,51);
    R3(d,e,a,b,c,52); R3(c,d,e,a,b,53); R3(b,c,d,e,a,54); R3(a,b,c,d,e,55);
    R3(e,a,b,c,d,56); R3(d,e,a,b,c,57); R3(c,d,e,a,b,58); R3(b,c,d,e,a,59);
    R4(a,b,c,d,e,60); R4(e,a,b,c,d,61); R4(d,e,a,b,c,62); R4(c,d,e,a,b,63);
    R4(b,c,d,e,a,64); R4(a,b,c,d,e,65); R4(e,a,b,c,d,66); R4(d,e,a,b,c,67);
    R4(c,d,e,a,b,68); R4(b,c,d,e,a,69); R4(a,b,c,d,e,70); R4(e,a,b,c,d,71);
    R4(d,e,a,b,c,72); R4(c,d,e,a,b,73); R4(b,c,d,e,a,74); R4(a,b,c,d,e,75);
    R4(e,a,b,c,d,76); R4(d,e,a,b,c,77); R4(c,d,e,a,b,78); R4(b,c,d,e,a,79);

    /* Add the working vars back into context.state[] */
    state[0] += a;
    state[1] += b;
    state[2] += c;
    state[3] += d;
    state[4] += e;

    /* Wipe variables */
    a = b = c = d = e = 0;
}

/* SHA1Init - Initialize new context */
static void SHA1_Init(SHA1_CTX* context)
{
    /* SHA1 initialization constants */
    context->state[0] = 0x67452301;
    context->state[1] = 0xEFCDAB89;
    context->state[2] = 0x98BADCFE;
    context->state[3] = 0x10325476;
    context->state[4] = 0xC3D2E1F0;
    context->count[0] = 0;
  	context->count[1] = 0;
}

/* Run your data through this. */
static void SHA1_Update(SHA1_CTX* context, const uint8_t* data, const size_t len)
{
    size_t i, j;

    j = (context->count[0] >> 3) & 63;
    if ((context->count[0] += len << 3) < (len << 3)) context->count[1]++;

    context->count[1] += (len >> 29);

    if ((j + len) > 63) 
  {
        memcpy(&context->buffer[j], data, (i = 64-j));
        SHA1_Transform(context->state, context->buffer);

        for ( ; i + 63 < len; i += 64) 
    {
            SHA1_Transform(context->state, data + i);
        }

        j = 0;
    }
    else i = 0;
    memcpy(&context->buffer[j], &data[i], len - i);
}

	void *
work_thread (void *arg)
{
	long i, num = 0;
	unsigned long pid = (unsigned long) arg;
	unsigned long long  start, end;
	char buf[HASHBUF];
	SHA1_CTX ctx;

	memset (buf, 0x1, HASHBUF);
	SHA1_Init (&ctx);

	while (!start_thread)
		pause ();

	unsigned int aux;
	start = __builtin_ia32_rdtscp (&aux);
	for (i = 0; stop_flag != 1 && i < iterations; i++)
	{
		lock();
		SHA1_Update(&ctx, (uint8_t *)buf, HASHBUF);
		unlock();
		wait_a_bit (delay_time_unlocked);
		num++;
	}
	end = __builtin_ia32_rdtscp (&aux);
	gcount[pid].diff = end - start;
	gcount[pid].total = num;

	return NULL;
}

void
test_threads (int numthreads)
{
	start_thread = 0;
	stop_flag = 0;

	memory_barrier ();

	pthread_t thr[numthreads];
	int i;

	for (i = 0; i < numthreads; i++)
	{
		pthread_attr_t attr;
		pthread_attr_init (&attr);
		cpu_set_t set;
		CPU_ZERO (&set);
		(void)CPU_SET (i, &set);
		pthread_attr_setaffinity_np (&attr, sizeof(cpu_set_t), &set);
		pthread_create (&thr[i], &attr, ops->test, (void *)(long)i);
	}

	memory_barrier ();
	start_thread = 1;
	memory_barrier ();
	sched_yield ();

	if (constant_time) {
		struct timespec ts = {
			ts.tv_sec = constant_time,
			ts.tv_nsec = 0
		};
		clock_nanosleep (CLOCK_MONOTONIC, 0, &ts, NULL);
		memory_barrier ();
		stop_flag = 1;
	}

	for (i = 0; i < numthreads; i++)
		pthread_join (thr[i], NULL);
}

struct ops hashwork_ops =
{
	.test = work_thread,
};

struct ops *ops;

	static struct count
total_stats (int numthreads)
{
	int i;
	unsigned long long total = 0;

	memset (gcount, 0, sizeof(gcount[0]) * numthreads);

	unsigned long long start, end, diff;
	unsigned int aux;

	start = __builtin_ia32_rdtscp (&aux);
	test_threads (numthreads);
	end = __builtin_ia32_rdtscp (&aux);
	diff = end - start;

	for (i = 0; i < numthreads; i++)
		total += gcount[i].total;
//	total = get_maximum_value (gcount, numthreads);

	struct count cost = { total, diff };
	return cost;
}

static int get_contented_thread_num (int numthreads, struct count *count)
{
	int i;
	struct count res;
	
	res = total_stats (1);
	count->total = res.total;
	count->diff = res.diff;
	for (i = 2; i <= numthreads; i++)
	{
		res = total_stats (i);
		if (res.total > count->total) {
			count->total = res.total;
			count->diff = res.diff;
		}
		else
			break;
	}

	return i;
}

	int
main (void)
{
	int numthreads = sysconf (_SC_NPROCESSORS_ONLN);
	if (numthreads < 8)
		return 1;

	ops = &hashwork_ops;

	if (posix_memalign ((void **)&gcount, 4096,
			sizeof(gcount[0]) * numthreads))
		exit(-1);

	struct count curr, best;
	double diff;
	int i, contention, last = numthreads;

	contention = get_contented_thread_num (numthreads, &best);
	printf("Best result with thread number: %d, total iterations: %lld\n",
			contention - 1, best.total);

	for (i = contention; i <= numthreads; i++)
	{
		last = i;
		curr = total_stats (i);
		diff = best.total - curr.total;
		/* Skip the case if diff < 0.  */
		if (diff < 0)
			continue;
		diff /= best.total;
		diff *= 100;
		printf (" threads number:%4d : %16lld, %0.1f%%\n",
				i, curr.total, diff);
		if ((i* 2)< numthreads)
			i = i * 2;
		else
			i = i + 16;
	}

	if (last != numthreads) {
		i = numthreads;
		curr = total_stats (i);
		diff = best.total - curr.total;
		diff /= best.total;
		diff *= 100;
		printf (" threads number:%4d : %16lld, %0.1f%%\n",
			i, curr.total, diff);
	}
	return 0;
}
